In [54]:
import pandas as pd
combined = pd.read_pickle('../../../combined')
combined.head()

# integrate to new RIS anootated
anno_RIS = pd.read_excel('../../EC_amr_anotateRIS20170710.xlsx')
anno_RIS.head()

# remove space in categoricals
for i in list(combined.columns.values):
    if '_ris' in str(i):
        combined[i] = combined[i].cat.rename_categories(['R','I','S'])
        combined[i] = combined[i].cat.add_categories(['cannot determine'])

In [56]:
# mapping
for index, row in anno_RIS.iterrows():
    antibiotic = row['ANTIBIOTIC'] + '_ris'
    #print(combined.ix[row['GENOME_ID'],antibiotic], row['SIR'])
    combined.ix[row['GENOME_ID'],antibiotic] = row['SIR']

In [60]:
# all E.coli
ecoli_card = combined.loc[list(set(list(anno_RIS['GENOME_ID']))),:]

In [65]:
ecoli_card.head()

,3000010,3000013,3000024,3000027,3000074,3000124,3000149,3000165,3000168,3000174,...,minocycline_mic,nitrofurantoin_mic,piperacillin_mic,piperacillin-tazobactam_mic,polymyxin B_mic,tetracycline_mic,ticarcillin/clavulanate_mic,tigecycline_mic,tobramycin_mic,trimethoprim-sulfamethoxazole_mic
ID,,,,,,,,,,,,,,,,,,,,,
1328432.3,0,0,1,1,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328433.3,0,0,1,1,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328434.3,0,0,1,1,1,0,0,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328436.3,0,0,1,1,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328437.3,0,0,1,1,1,0,0,0,0,0,...,NaN,NaN,NaN,64,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
ecoli_card.to_excel('../../ec_card.xlsx')